### ISSUE TITLE
Getting error `Access to the path 'obj\\berry' is denied`

### ISSUE THREAD

**Issue by replaysMike** [NexarDeveloper/nexar-templates#2] opened 2023-03-27 22:16 UTC
I've followed the steps required for generating the nexar-console-supply template and generated a test project. I've manually installed the StrawberryShake.Tools using `dotnet tool install --global StrawberryShake.Tools` as the builtin `.config/dotnet-tools.json` doesn't appear to do anything.

I managed to get everything working once, but after running `dotnet tool restore` and `dotnet graphql update` I keep getting this 

```
Access to the path 'obj\\berry' is denied.	Nexar.Client
```

any ideas?

**Comment by replaysMike** [comment] 2023-03-27 22:25
It would seem that running VS in Administrator mode will get the error to go away (not ideal), but there are lots of errors after upgrading `StrawberryShake.CodeGeneration.CSharp.Analyzers` and `StrawberryShake.Transport.Http` to latest (non-prerelease) versions.

```
1>B:\gitrepo\personalcode\Nexar\Nexar.Client\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\NexarClient.StrawberryShake.cs(188,21,188,51): error CS0234: The type or namespace name 'Helper' does not exist in the namespace 'StrawberryShake' (are you missing an assembly reference?)
1>B:\gitrepo\personalcode\Nexar\Nexar.Client\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\NexarClient.StrawberryShake.cs(56,734,56,879): error CS1503: Argument 3: cannot convert from 'StrawberryShake.IOperationStore' to 'System.Func<StrawberryShake.IResultPatcher<System.Text.Json.JsonDocument>>'
1>B:\gitrepo\personalcode\Nexar\Nexar.Client\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\NexarClient.StrawberryShake.cs(56,881,56,889): error CS1503: Argument 4: cannot convert from 'StrawberryShake.ExecutionStrategy' to 'StrawberryShake.IOperationStore'
```

**Comment by replaysMike** [comment] 2023-03-27 23:04
Errors are resolved if I stick with only version `12.17.0` of the StrawberryShake libraries. Needing to run as Administrator is a bit of a problem for CI pipelines, still can't seem to get around that with StrawberryShake. This seems like a fairly brittle way to go about things, maybe I can find an alternative to using that package for GraphQL.

**Comment by nightroman** [comment] 2023-03-27 23:10
@replaysMike It's this issue -- https://github.com/ChilliCream/graphql-platform/issues/3653
The workaround is add this to your project
```
    <BaseIntermediateOutputPath>$(MSBuildProjectExtensionsPath)</BaseIntermediateOutputPath>
```
The issue is resolved in v13 but it has it's own (minor) issues. I'd wait for 13.1, expected soon.

**Comment by replaysMike** [comment] 2023-03-27 23:15
Thanks for the response @nightroman - I managed to remove all packages from the Nexar.Client and replaced with this: `<PackageReference Include="StrawberryShake.Server" Version="13.0.5" />`.

Then:
```ps
cd .\Nexar.Client
dotnet new tool-manifest --force
dotnet graphql update
```

After this I was able to build and run without issues. Hopefully I don't run unto those pesky v13 issues you mentioned, but I'll likely know shortly as I integrate the api.

**Comment by nightroman** [comment] 2023-03-27 23:15
NB But if you want using v13 (we do in own projects) then
- client packages changed, see https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13
- `graphql update` is not working, use `graphql download` for updating, for now

**Comment by replaysMike** [comment] 2023-03-27 23:16
I see thanks for the heads up

**Closed as completed** 2023-03-27 23:20 UTC

**Comment by nightroman** [comment] 2023-03-28 00:15
I have added the workaround to templates.
But I hope we'll move to v13.1 soon and it will not be needed.
